version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=SummerProject
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tgbot:
    build:
      context: .
      dockerfile: tgbot.Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=postgres
      - DATABASE_NAME=SummerProject
    ports: 
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  parcer:
    build:
      context: .
      dockerfile: parcer.Dockerfile
    environment:
      - USER_AGENT=${USER_AGENT}
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=postgres
    depends_on:
      database:
        condition: service_healthy

volumes:
  db-data:

name: summer_project